baseURL = 'https://gplanchat.github.io/ddd-adventure/'
languageCode = 'fr-fr'
title = 'DDD Adventure'

[params]
  # Footer configuration
  [params.footer]
    copyright = "© :YEAR: Grégory Planchat. Tous droits réservés."

  # Sponsors configuration
  [params.sponsors]
    enable = true
    title = "Nos Sponsors"
    subtitle = "Merci à nos partenaires qui soutiennent cette initiative"
    sponsors = [
      { name = "Kiboko", url = "https://kiboko.fr", logo = "kiboko-logo.png" },
      { name = "Gyroscops", url = "https://gyroscops.com", logo = "gyroscops-logo.png" }
    ]

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
